repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        entry: dotnet
        pass_filenames: true
        args: [format, --verify-no-changes, --include]
        language: system
        types_or: [c#]
